### ISSUE TITLE
Использовать сервисы

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#10]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/models/user.py#L248

Полезный подход: выводить бизнес-логику в сервисы. В пакете приложения создается пакет services, в нем ты реализуешь разные небольшие классы сервисов. Каждый отвечает за 1 простую функцию. Это позволяет не перегружать модели. Важно обратить внимание на то, что там нельзя выполнять прямой импорт моделей. Только через apps.get_model('app.Model')

**Comment by pianoyeg94** [comment]
Спасибо большое за гайдлайн, буду теперь знать
