### ISSUE TITLE
Создание юзера и компании вместе

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#12]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/models/company.py#L20

Не выглядит хорошим решением. Надо пересмотреть всю логику, которая предшествует необходимости это делать. Обычно юзер у тебя уже есть, либо создается заранее. Как минимум от метода с именем create_company_account не ждут, что он еще и юзеров будет в базу добавлять.

**Comment by pianoyeg94** [comment]
Спасибо, справедливо, действительно нелогично
