### ISSUE TITLE
Зачем Thread если есть celery

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#14]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/signals.py#L51

Зачем это все городить?

**Comment by pianoyeg94** [comment]
В комментах к этому модулю как раз написано, что желательно бы все перенести в Celery, чтобы разгрузить WSGI процесс. Еще не успел сделать
