### ISSUE TITLE
Профиль может никогда не появиться 

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#15]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/signals.py#L41

Если при первом создании юзера, профиль по каким-то причинам не сохраниться, он больше не попытается создаться. 
Лучше при каждом сохранении проверять если ли профиль и заводить его, если нет.

**Comment by pianoyeg94** [comment]
Спасибо, даже мысли такой не возникло, поправлю
