### ISSUE TITLE
Логика совсем не там находится

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#16]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/signals.py#L91

1) Лучше всего тут вызывать celery
2) Если надо, чтобы это работало в API и было в одном потоке, то делать это надо в сериализаторах или вьюхах. Но никак не в сигналах. Сигнал, который рейзит экепшен для API это ваще сюр какой-то. Ошибку там потом отловить будет невозможно.

**Comment by fffffrolov** [comment]
Там по стилю кода напрашивается сервис для создания компании, которая обернута в транзакцию

**Comment by pianoyeg94** [comment]
Тут полностью согласен, накосячил
