### ISSUE TITLE
Использовать вьюсеты 

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#17]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/api/views/user.py#L1

https://www.django-rest-framework.org/api-guide/viewsets/
Объем кода будет в 4 раза меньше.

**Comment by pianoyeg94** [comment]
Тут полностью согласен
