### ISSUE TITLE
Слишком много написано руками по правам

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#18]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/shared/permissions.py#L50

Когда так много приходится писать в джанге самому, надо остановиться и поискать решение. Варианты: 
попроще: django-rules, django-guardian
пожирнее: django-rbac, casbin.org

**Comment by pianoyeg94** [comment]
Написал свои, чтобы они были легковесные и легко кастомизируемые именно под мои нужды. Просто в таких часто тяжеловесных пакетах для джанги, потом будешь больше заниматься борьбой с их кодом и разбором, а как же они все там реализовали, если вдруг захочешь каким-то нетривиальным способом что-то под себя сделать.  Но да, я понимаю, что это не "по-джанговому"

**Comment by fffffrolov** [comment]
Да просто много лишнего. Посмотри django-rules. Ничего тяжелого там нет, кода раз 100 будет меньше

**Comment by pianoyeg94** [comment]
Спасибо, гляну)))
