### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#20]
![b108179b0a525bd01b55739bc1ede235](https://user-images.githubusercontent.com/36497660/90216966-2b059400-de2a-11ea-9bb7-a14e1ea273a6.jpg)

тесты должны быть на все. при таком огромном количестве кода тем более. На работу моделей, каждого метода, прав в API и т.д.

**Comment by pianoyeg94** [comment]
Это да, начал писать тесты слишком поздно и не успел покрыть все, большой косяк
