### ISSUE TITLE
Зачем было переписывать этот метод?

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#7]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/models/user.py#L44

**Comment by pianoyeg94** [comment]
Переписано для того, чтобы избавиться от лишнего поля username, которое мне абсолютно не нужно в базе и т.д. - иначе никак не избавишься от кучи дефолта в юзер моделях, который для проекта абсолютно лишний
