### ISSUE TITLE
Зачем вручную именовать таблицы и индексы?

### ISSUE THREAD

**Issue by fffffrolov** [pianoyeg94/swagger_whats_new_backend#9]
https://github.com/pianoyeg94/swagger_whats_new_backend/blob/1ae560c0104941367dda73851ab532a04b82f712/app/apps/accounts/models/user.py#L178

**Comment by pianoyeg94** [comment]
С точки зрения базы, логичней чтобы таблицы и индексы назывались именно так. Стандартные названия "режут глаз" при работе напрямую с базой

**Comment by fffffrolov** [comment]
А у тебя возникали такие такие задачи, где надо работать напрямую?

**Comment by pianoyeg94** [comment]
Были планы , возможно, некоторые "сложные" запросы вынести во view в базе данных и ,возможно, что-то в хранимые процедуры. Но пока ,проинспектив, какие запросы в базу генерит Джанго в случае кучи джоинов, подзапросов и тд, меня все устравивает по их оптимальности. Больше мысли о будущем, так скажем. Ну и по нуждам тестирования иногда приходится лазить напрямую в базу.
Плюс это "забота" об эфемерных в данном случае тестировщиках и базовиках, которые все таки взамимодействуют с базой напрямую
